name: pytorch
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pip
  - pytorch
  - pytorch-cuda=11.7
  - sacremoses
  - sacrebleu
  - isort
  - black
  - ruff
  - mypy
  - tqdm
  - spacy
  - pip:
    - subword-nmt
    - unbabel-comet